In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import scipy.stats as stats
from math import exp, log
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
import warnings
warnings.filterwarnings('ignore')
pd.options.display.float_format = "{:,.5f}".format

# Operaciones con matrices

In [2]:
A = [[1.,-2.,0.],[-2.,5.,0.],[0.,0.,2.]]
B = [[-2.,-7.,10.0],[8.,0.5,0.3],[-5,-2,4]]
A, B = np.asarray(A), np.asarray(B)
print(A)
print(B)

[[ 1. -2.  0.]
 [-2.  5.  0.]
 [ 0.  0.  2.]]
[[-2.  -7.  10. ]
 [ 8.   0.5  0.3]
 [-5.  -2.   4. ]]


In [3]:
#1. Suma
C = A + B
print("La suma de las matrices es igual a")
print(C)

La suma de las matrices es igual a
[[-1.  -9.  10. ]
 [ 6.   5.5  0.3]
 [-5.  -2.   6. ]]


In [4]:
#1. Resta
C = A - B
print("La resta de las matrices es igual a")
print(C)

La resta de las matrices es igual a
[[  3.    5.  -10. ]
 [-10.    4.5  -0.3]
 [  5.    2.   -2. ]]


In [5]:
#3. Multiplicación
C = np.dot(A,B)
print("El producto de las matrices es igual a")
print(C)

El producto de las matrices es igual a
[[-18.   -8.    9.4]
 [ 44.   16.5 -18.5]
 [-10.   -4.    8. ]]


In [6]:
#Notar que la siguiente expresión es la multilpicación término a término
C = A*B
print("El producto término a término de las matrices es igual a")
print(C)

El producto término a término de las matrices es igual a
[[ -2.   14.    0. ]
 [-16.    2.5   0. ]
 [ -0.   -0.    8. ]]


In [7]:
#4. Determinante
C = np.linalg.det(A)
print("El determinante es igual a",C)

El determinante es igual a 2.0


In [8]:
#5. Inversa de una matriz
Ainv = np.linalg.inv(A)
print("La matriz A es igual a")
print(A)
print("La inversa de la matriz A es igual a")
print(Ainv)
print("El producto de la matriz A con su inversa es igual a")
print(np.dot(A,Ainv))

La matriz A es igual a
[[ 1. -2.  0.]
 [-2.  5.  0.]
 [ 0.  0.  2.]]
La inversa de la matriz A es igual a
[[ 5.   2.  -0. ]
 [ 2.   1.   0. ]
 [ 0.   0.   0.5]]
El producto de la matriz A con su inversa es igual a
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
A = [[1.,-2.,0.],[-2.,5.,0.],[0.,0.,2.]]
A = np.asarray(A)
I = [[1,0,0],[0,1,0],[0,0,1]]
I = np.asarray(I)
print(I)
I = np.identity(3)
print(I)
print("La matriz A es igual a")
print(A)
print("El producto de la matriz identidad por la matriz A es igual a")
print(np.dot(I,A))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
La matriz A es igual a
[[ 1. -2.  0.]
 [-2.  5.  0.]
 [ 0.  0.  2.]]
El producto de la matriz identidad por la matriz A es igual a
[[ 1. -2.  0.]
 [-2.  5.  0.]
 [ 0.  0.  2.]]


In [10]:
#Inversa de una matriz con determinante cero
A = [[1,0,0],[0,0,0],[0,0,10]]
A = np.asarray(A)
C = np.linalg.det(A)
print("El determinante es igual a",C) 
#Ainv = np.linalg.inv(A)

El determinante es igual a 0.0


# Valores y vectores propios

In [11]:
A = [[1,1],[4,1]]
A = np.asarray(A)
val_prop, vec_prop = np.linalg.eig(A)
vec_prop = np.matrix.transpose(vec_prop)
n = len(val_prop)
for i in range(n):
    print("-----------------------------------------------------")
    print("Vector propio " + str(i+1) + " = %s" %vec_prop[i])
    print("Valor propio " + str(i+1) + " = %s" %val_prop[i])
print("Verificaciones")
for i in range(n):
    Ax = np.inner(A,vec_prop[i])
    vaux = []
    for j in range(len(vec_prop[i])):
        vaux.extend([val_prop[i]*vec_prop[i][j]])
    print("-----------------------------------------------------")
    print("Matriz por vector propio " + str(i+1) + " = %s" %Ax)
    print("Valor propio por vector propio " + str(i+1) + " = %s" %vaux)

-----------------------------------------------------
Vector propio 1 = [0.4472136  0.89442719]
Valor propio 1 = 3.0000000000000004
-----------------------------------------------------
Vector propio 2 = [-0.4472136   0.89442719]
Valor propio 2 = -0.9999999999999996
Verificaciones
-----------------------------------------------------
Matriz por vector propio 1 = [1.34164079 2.68328157]
Valor propio por vector propio 1 = [1.3416407864998745, 2.683281572999748]
-----------------------------------------------------
Matriz por vector propio 2 = [ 0.4472136  -0.89442719]
Valor propio por vector propio 2 = [0.4472135954999576, -0.8944271909999155]
